packages:
  - 'src/backend/*'
  - 'src/frontend'
  - 'infra'
  - 'packages/*'

catalog:
  typescript: 5.9.3
  vitest: 4.0.17
  zod: 4.3.5
  aws-cdk-lib: 2.235.1
  constructs: 10.4.5
  esbuild: 0.25.5
  tsx: 4.20.3
  tsdown: 0.19.0

onlyBuiltDependencies:
  - esbuild
